spring:

  application:
    name: api-gateway

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jwt:
    secret: 4b6050b9a135b722dab15dabc4f22d246b705030ec5af354221550b89c735ed8

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Tour Booking Service
        url: /aggregate/tour-booking-service/v3/api-docs
      - name: Tour Service
        url: /aggregate/tour-service/v3/api-docs
      - name: Tour User Service
        url: /aggregate/tour-user-service/v3/api-docs
    validator-url: null
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: api-gateway-instance
    prefer-ip-address: true

logging:
  level:
    com.netflix.discovery: TRACE
    com.netflix.eureka: TRACE

server:
  port: 8080

