server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres-tour-notification:5432/tour_notification_service_db
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      properties:
        spring.json.trusted.packages: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
