server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres-tour-booking:5432/tour_booking_service_db
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092

  tour:
    service:
      url: http://tour-service:8081

    user:
      service:
        url: http://tour-user-service:8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
