version: '3.9'

volumes:
  pg_tour_user:

services:
  tour_user_service_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tour_user_service_db
    volumes:
      - pg_tour_user:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"